services:
  # Backend Web Service
  - type: web
    name: boulevard-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: ./render-build.sh
    startCommand: node index.js
    healthCheckPath: /api/stats/cities/popular
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render assigns its own port
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        value: econest_session_secret_key
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: boulevard-frontend
    env: static
    region: singapore
    plan: free
    rootDir: frontend
    buildCommand: npm install && VITE_APP_RAZORPAY_KEY_ID=rzp_test_CfHijwdCzAevEK VITE_API_URL=https://boulevard-api.onrender.com/api npx vite build --config vite.config.minimal.js
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
      - type: rewrite
        source: /**/*
        destination: /index.html
    headers:
      - path: /**
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
    envVars:
      - key: VITE_APP_RAZORPAY_KEY_ID
        value: rzp_test_CfHijwdCzAevEK
      - key: VITE_API_URL
        value: https://boulevard-api.onrender.com/api
